spring.application.name=api-gateway
server.port=8090
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=ms_socio_route
spring.cloud.gateway.routes[0].uri=lb://MS-SOCIO
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/gimnasio/socios/**

spring.cloud.gateway.routes[1].id=ms_plan_route
spring.cloud.gateway.routes[1].uri=lb://MS_PLAN
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/gimnasio/planes/**

spring.cloud.gateway.routes[2].id=ms_inscripcion_route
spring.cloud.gateway.routes[2].uri=lb://MS_INSCRIPCION
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/gimnasio/inscripciones/**