server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ms_socio_route
          uri: lb://ms-socio
          predicates:
            - Path=/api/gimnasio/socios/**, /api/gimnasio/socios/direcciones/**

        - id: ms_plan_route
          uri: lb://ms-plan
          predicates:
            - Path=/api/gimnasio/planes/**

        - id: ms_inscripcion_route
          uri: lb://ms-inscripcion
          predicates:
            - Path=/api/gimnasio/inscripciones/**

        - id: ms_pago_route
          uri: lb://ms-pago
          predicates:
            - Path=/api/gimnasio/pagos/**

        - id: ms_evaluacion_route
          uri: lb://ms-evaluacion
          predicates:
            - Path=/api/gimnasio/evaluaciones/**

        - id: ms_socio_openapi
          uri: lb://ms-socio
          predicates:
            - Path=/api/gimnasio/socios/v3/api-docs
          filters:
            - RewritePath=/api/gimnasio/socios/v3/api-docs, /v3/api-docs

        - id: ms_plan_openapi
          uri: lb://ms-plan
          predicates:
            - Path=/api/gimnasio/planes/v3/api-docs
          filters:
            - RewritePath=/api/gimnasio/planes/v3/api-docs, /v3/api-docs

        - id: ms_inscripcion_openapi
          uri: lb://ms-inscripcion
          predicates:
            - Path=/api/gimnasio/inscripciones/v3/api-docs
          filters:
            - RewritePath=/api/gimnasio/inscripciones/v3/api-docs, /v3/api-docs

        - id: ms_pago_openapi
          uri: lb://ms-pago
          predicates:
            - Path=/api/gimnasio/pagos/v3/api-docs
          filters:
            - RewritePath=/api/gimnasio/pagos/v3/api-docs, /v3/api-docs

        - id: ms_evaluacion_openapi
          uri: lb://ms-evaluacion
          predicates:
            - Path=/api/gimnasio/evaluaciones/v3/api-docs
          filters:
            - RewritePath=/api/gimnasio/evaluaciones/v3/api-docs, /v3/api-docs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

    use-root-path: true
    urls:
      - name: Microservicio Socio
        url: /api/gimnasio/socios/v3/api-docs
      - name: Microservicio Plan
        url: /api/gimnasio/planes/v3/api-docs
      - name: Microservicio Inscripcion
        url: /api/gimnasio/inscripciones/v3/api-docs
      - name: Microservicio Evaluacion
        url: /api/gimnasio/evaluaciones/v3/api-docs
      - name: Microservicio Pago
        url: /api/gimnasio/pagos/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/