server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ms_socio_route
          uri: lb://ms-socio
          predicates:
            - Path=/api/gimnasio/socios/**, /api/gimnasio/socios/direcciones/**

        - id: ms_plan_route
          uri: lb://ms-plan
          predicates:
            - Path=/api/gimnasio/planes/**

        - id: ms_inscripcion_route
          uri: lb://ms-inscripcion
          predicates:
            - Path=/api/gimnasio/inscripciones/**

        - id: ms_pago_route
          uri: lb://ms-pago
          predicates:
            - Path=/api/gimnasio/pagos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/